{{- if .Values.persistence.enabled -}}
{{- range .Values.persistence.paths }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  accessModes:
    - {{ $.Values.persistence.accessMode }}
  {{- if $.Values.persistence.storageClass }}
  storageClassName: {{ $.Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
{{- end }}
{{- end }}
