{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fortinet.fullname" . }}-redis
  labels:
    {{- include "fortinet.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "fortinet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}