version: '3.8'

services:
  # Watchtower - 자동 컨테이너 업데이트 서비스
  watchtower:
    image: containrrr/watchtower:latest
    container_name: fortinet-watchtower
    restart: unless-stopped
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json:ro
    
    environment:
      # 기본 설정
      - WATCHTOWER_POLL_INTERVAL=300  # 5분마다 체크
      - WATCHTOWER_CLEANUP=true  # 이전 이미지 자동 삭제
      - WATCHTOWER_INCLUDE_STOPPED=false  # 중지된 컨테이너 제외
      - WATCHTOWER_REVIVE_STOPPED=false  # 중지된 컨테이너 재시작 안함
      
      # 업데이트 전략
      - WATCHTOWER_ROLLING_RESTART=true  # 롤링 재시작
      - WATCHTOWER_TIMEOUT=60s  # 타임아웃 설정
      - WATCHTOWER_STOP_TIMEOUT=10s  # 컨테이너 중지 타임아웃
      
      # 스코프 설정 (fortinet 컨테이너만 업데이트)
      - WATCHTOWER_SCOPE=fortinet-scope
      
      # 알림 설정
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_EMAIL_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_EMAIL_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_EMAIL_PORT:-587}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_EMAIL_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_EMAIL_PASSWORD}
      
      # HTTP API 설정
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN:-your-secure-token}
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - WATCHTOWER_HTTP_API_UPDATE_POLL_INTERVAL=30
      
      # Docker 설정
      - DOCKER_CONFIG=/config.json
      - DOCKER_HOST=unix:///var/run/docker.sock
      
      # 레지스트리 인증
      - REPO_USER=${REGISTRY_USERNAME}
      - REPO_PASS=${REGISTRY_PASSWORD}
    
    ports:
      - "8080:8080"  # HTTP API
    
    networks:
      - fortinet-network
    
    labels:
      # Watchtower 자체는 업데이트 제외
      - "com.centurylinklabs.watchtower.enable=false"
      - "com.fortinet.nextrade.service=watchtower"
      - "com.fortinet.nextrade.description=Auto-update service"
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  fortinet-network:
    external: true
    name: fortinet-network