version: '3.8'

services:
  # FortiGate Nextrade Application
  fortinet-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "7777:7777"
    environment:
      - APP_MODE=test
      - OFFLINE_MODE=true
      - WEB_APP_PORT=7777
      - FLASK_ENV=development
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - fortinet-dev

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fortinet-dev

  # Prometheus (Optional)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - fortinet-dev

volumes:
  redis_data:
  prometheus_data:

networks:
  fortinet-dev:
    driver: bridge