# =============================================================================
# Watchtower - 자동 컨테이너 업데이트 서비스
# registry.jclee.me에서 이미지 변경 감지 시 자동 업데이트
# =============================================================================

version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-fortinet
    restart: unless-stopped
    
    # Docker 소켓 접근 권한
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    environment:
      # 업데이트 간격 (기본: 5분)
      - WATCHTOWER_POLL_INTERVAL=300
      
      # 대상 컨테이너 (fortinet 컨테이너만)
      - WATCHTOWER_SCOPE=fortinet-scope
      
      # 레지스트리 인증
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=fortinet-server
      - WATCHTOWER_NOTIFICATION_TITLE_TAG=FortiGate Nextrade
      
      # 로그 레벨
      - WATCHTOWER_LOG_LEVEL=info
      
      # 자동 정리 활성화 (이전 이미지 제거)
      - WATCHTOWER_CLEANUP=true
      
      # 포함할 컨테이너만 업데이트
      - WATCHTOWER_LABEL_ENABLE=true
      
      # 즉시 실행 후 주기적 실행
      - WATCHTOWER_RUN_ONCE=false
      
      # 타임존 설정
      - TZ=Asia/Seoul
    
    labels:
      - "com.centurylinklabs.watchtower.scope=fortinet-scope"
      - "com.fortinet.nextrade.service=watchtower"
      - "com.fortinet.nextrade.description=Auto-update service"
    
    networks:
      - fortinet-network

networks:
  fortinet-network:
    external: true
    name: fortinet-network