apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patchesStrategicMerge:
  - deployment-patch.yaml

namespace: fortinet

commonLabels:
  environment: production
  tier: production

commonAnnotations:
  app.kubernetes.io/version: "v1.0.0"
  app.kubernetes.io/environment: production

images:
  - name: registry.jclee.me/fortinet
    newTag: latest

replicas:
  - name: fortinet
    count: 3

configMapGenerator:
  - name: fortinet-production-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - MAX_WORKERS=8
      - WORKER_TIMEOUT=120