apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namespace: fortinet

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: registry.jclee.me/fortinet
    newTag: latest  # This will be updated by CI/CD

configMapGenerator:
  - name: fortinet-config
    behavior: merge
    literals:
      - APP_MODE=production
      - OFFLINE_MODE=false
      - WEB_APP_PORT=7777
      - WEB_APP_HOST=0.0.0.0