apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet
  namespace: argocd
  labels:
    app: fortinet
    env: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    chart: fortinet
    targetRevision: "*"  # 최신 버전 자동 사용
    helm:
      releaseName: fortinet
      values: |
        replicaCount: 2
        image:
          repository: registry.jclee.me/fortinet
          tag: "latest"
          pullPolicy: Always
        imagePullSecrets:
          - name: harbor-registry
        service:
          type: NodePort
          nodePort: 30777
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        fortinet:
          appMode: production
          webPort: 7777
          webHost: "0.0.0.0"
          offlineMode: false
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10