apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet
  namespace: argocd
  labels:
    app: fortinet
    env: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    targetRevision: 1.1.2
    chart: fortinet
    helm:
      releaseName: fortinet
      values: |
        replicaCount: 1
        image:
          pullPolicy: Always
        service:
          type: NodePort
          nodePort: 30777
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        env:
          APP_MODE: production
          OFFLINE_MODE: "false"
          WEB_APP_PORT: "7777"
        persistence:
          enabled: false
        autoscaling:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10