apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet-fortinet
  namespace: argocd
  labels:
    app: fortinet
    env: fortinet
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/jclee94/fortinet.git
    path: charts/fortinet
    targetRevision: HEAD
    helm:
      releaseName: fortinet
      values: |
        replicaCount: 2
        image:
          pullPolicy: Always
        service:
          type: NodePort
          nodePort: 30777
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          APP_MODE: production
          OFFLINE_MODE: "false"
          WEB_APP_PORT: "7777"
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
