# FortiGate Nextrade - Production Environment (NAS DEPLOYMENT)
# CLAUDE.md v8.7.0 compliant production configuration

version: '3.8'

services:
  app:
    image: ${REGISTRY:-registry.jclee.me}/${IMAGE_NAME:-fortinet}:latest
    container_name: ${IMAGE_NAME:-fortinet}-app-1
    restart: unless-stopped
    ports:
      - "${APP_PORT:-7777}:${APP_PORT:-7777}"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./ssl/certs:/app/ssl/certs:ro
    environment:
      - APP_MODE=production
      - FLASK_ENV=production
      - PORT=${APP_PORT:-7777}
      - TZ=Asia/Seoul
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # FortiGate/FortiManager Configuration
      - FORTIGATE_HOST=${FORTIGATE_HOST:-192.168.1.99}
      - FORTIGATE_TOKEN=${FORTIGATE_TOKEN:-}
      - FORTIMANAGER_HOST=${FORTIMANAGER_HOST:-192.168.1.100}
      - FORTIMANAGER_USERNAME=${FORTIMANAGER_USERNAME:-admin}
      - FORTIMANAGER_PASSWORD=${FORTIMANAGER_PASSWORD:-}
      # Database Configuration
      - DATABASE_URL=sqlite:///data/fortinet.db
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    networks:
      - ${IMAGE_NAME:-fortinet}-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:${APP_PORT:-7777}/api/health\", timeout=5).read()'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    stop_grace_period: 1s
    labels:
      - "com.docker.compose.project=fortinet"
      - "com.docker.compose.service=app"
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
      - "com.centurylinklabs.watchtower.timeout=30s"
      - "com.centurylinklabs.watchtower.scope=${IMAGE_NAME:-fortinet}"

  redis:
    image: redis:7-alpine
    container_name: ${IMAGE_NAME:-fortinet}-redis-1
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - ${IMAGE_NAME:-fortinet}-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ${IMAGE_NAME:-fortinet}-network:
    driver: bridge
    name: ${IMAGE_NAME:-fortinet}-network

volumes:
  redis-data:
    name: ${IMAGE_NAME:-fortinet}-redis-data

# PRODUCTION DEPLOYMENT ONLY - FOR NAS (192.168.50.215)
# This configuration is optimized for production deployment via GitLab CI/CD
