version: '3.8'

services:
  fortinet:
    image: registry.jclee.me/fortinet:master-0dc25b6
    container_name: fortinet-optimized
    hostname: fortinet-app
    ports:
      - "7777:7777"
    environment:
      - APP_MODE=production
      - OFFLINE_MODE=false
      - WEB_APP_PORT=7777
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here-change-in-production}
      - FORTIMANAGER_HOST=${FORTIMANAGER_HOST:-}
      - FORTIGATE_HOST=${FORTIGATE_HOST:-}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - fortinet-network
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: fortinet-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - fortinet-network

  monitoring:
    image: prom/node-exporter:latest
    container_name: fortinet-node-exporter
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    restart: unless-stopped
    networks:
      - fortinet-network
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)'
    volumes:
      - /:/host:ro,rslave

networks:
  fortinet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  redis-data:
    driver: local