# =============================================================================
# FortiGate Nextrade - Standalone Docker Compose
# Self-contained deployment without external dependencies
# =============================================================================

version: '3.8'

services:
  # Single self-contained application
  fortinet-standalone:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    
    image: fortinet-standalone:latest
    container_name: fortinet-standalone
    hostname: fortinet-standalone
    restart: unless-stopped
    
    ports:
      - "7777:7777"
    
    environment:
      # Basic configuration - all others are embedded
      - APP_MODE=production
      - LOG_LEVEL=INFO
      - WEB_APP_PORT=7777
      
      # Standalone mode flags
      - STANDALONE_MODE=true
      - OFFLINE_MODE=true
      - USE_MEMORY_CACHE=true
      - REDIS_ENABLED=false
      
      # Optional overrides (usually not needed)
      - SECRET_KEY=${SECRET_KEY:-}  # Will be auto-generated if not provided
      - WORKERS=${WORKERS:-4}
      - TIMEOUT=${TIMEOUT:-120}
    
    # No volume mounts - everything is contained in the image
    # Data persistence happens inside the container
    # For backup, use docker cp or docker export
    
    # No dependencies on external services
    # No Redis, no external databases
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/api/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Memory limits for standalone operation
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    
    # Labels for management
    labels:
      - "com.fortinet.nextrade.mode=standalone"
      - "com.fortinet.nextrade.self-contained=true"
      - "com.fortinet.nextrade.no-volumes=true"
      - "com.fortinet.nextrade.no-external-deps=true"

# No networks needed - uses default bridge
# No volumes needed - everything is self-contained