# =============================================================================
# FortiGate Nextrade - Microservices Architecture
# MSA deployment with Kong Gateway, Consul, and RabbitMQ
# =============================================================================

version: '3.8'

services:
  # Kong Gateway - API Gateway
  kong-database:
    image: postgres:13-alpine
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - fortinet-msa
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    networks:
      - fortinet-msa

  kong:
    image: kong:latest
    container_name: kong-gateway
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"  # Proxy
      - "8001:8001"  # Admin API
      - "8002:8002"  # GUI
    networks:
      - fortinet-msa

  # Consul - Service Discovery
  consul:
    image: consul:latest
    container_name: consul
    command: agent -server -bootstrap -ui -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - fortinet-msa
    volumes:
      - consul-data:/consul/data

  # RabbitMQ - Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: fortinet
      RABBITMQ_DEFAULT_PASS: fortinet123
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    networks:
      - fortinet-msa
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # Redis - Shared Cache
  redis:
    image: redis:7.2-alpine
    container_name: redis-msa
    ports:
      - "6379:6379"
    networks:
      - fortinet-msa
    volumes:
      - redis-msa-data:/data

  # Auth Service
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - PORT=8081
      - CONSUL_URL=http://consul:8500
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fortinet:fortinet123@rabbitmq:5672
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - redis
      - rabbitmq
    networks:
      - fortinet-msa

  # FortiManager Service
  fortimanager-service:
    build:
      context: ./services/fortimanager
      dockerfile: Dockerfile
    container_name: fortimanager-service
    environment:
      - PORT=8082
      - CONSUL_URL=http://consul:8500
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fortinet:fortinet123@rabbitmq:5672
    ports:
      - "8082:8082"
    depends_on:
      - consul
      - redis
      - rabbitmq
    networks:
      - fortinet-msa

  # ITSM Service
  itsm-service:
    build:
      context: ./services/itsm
      dockerfile: Dockerfile
    container_name: itsm-service
    environment:
      - PORT=8083
      - CONSUL_URL=http://consul:8500
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fortinet:fortinet123@rabbitmq:5672
    ports:
      - "8083:8083"
    depends_on:
      - consul
      - redis
      - rabbitmq
    networks:
      - fortinet-msa

  # Monitoring Service
  monitoring-service:
    build:
      context: ./services/monitoring
      dockerfile: Dockerfile
    container_name: monitoring-service
    environment:
      - PORT=8084
      - CONSUL_URL=http://consul:8500
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fortinet:fortinet123@rabbitmq:5672
    ports:
      - "8084:8084"
    depends_on:
      - consul
      - redis
      - rabbitmq
    networks:
      - fortinet-msa

  # Security Service
  security-service:
    build:
      context: ./services/security
      dockerfile: Dockerfile
    container_name: security-service
    environment:
      - PORT=8085
      - CONSUL_URL=http://consul:8500
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fortinet:fortinet123@rabbitmq:5672
    ports:
      - "8085:8085"
    depends_on:
      - consul
      - redis
      - rabbitmq
    networks:
      - fortinet-msa

  # Analysis Service
  analysis-service:
    build:
      context: ./services/analysis
      dockerfile: Dockerfile
    container_name: analysis-service
    environment:
      - PORT=8086
      - CONSUL_URL=http://consul:8500
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fortinet:fortinet123@rabbitmq:5672
    ports:
      - "8086:8086"
    depends_on:
      - consul
      - redis
      - rabbitmq
    networks:
      - fortinet-msa

  # Configuration Service
  config-service:
    build:
      context: ./services/config
      dockerfile: Dockerfile
    container_name: config-service
    environment:
      - PORT=8087
      - CONSUL_URL=http://consul:8500
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://fortinet:fortinet123@rabbitmq:5672
    ports:
      - "8087:8087"
    depends_on:
      - consul
      - redis
      - rabbitmq
    networks:
      - fortinet-msa

networks:
  fortinet-msa:
    driver: bridge
    name: fortinet-msa-network

volumes:
  kong-db-data:
  consul-data:
  rabbitmq-data:
  redis-msa-data: