version: '3.8'

services:
  # Simple test setup for local validation
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fortinet
      POSTGRES_USER: fortinet
      POSTGRES_PASSWORD: fortinet123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fortinet"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.production
    environment:
      APP_MODE: test
      OFFLINE_MODE: true
      SECRET_KEY: test-secret-key
      DATABASE_URL: postgresql://fortinet:fortinet123@postgresql:5432/fortinet
      REDIS_URL: redis://redis:6379/0
    ports:
      - "7777:7777"
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy
