apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortinet
  namespace: fortinet
  labels:
    app: fortinet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortinet
  template:
    metadata:
      labels:
        app: fortinet
    spec:
      containers:
      - name: fortinet
        image: registry.jclee.me/fortinet:latest
        ports:
        - containerPort: 7777
          name: http
        env:
        - name: APP_MODE
          value: "production"
        - name: WEB_APP_PORT
          value: "7777"
        - name: OFFLINE_MODE
          value: "false"
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fortinet-data
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: harbor-registry