apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fortinet-application.yaml

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: kustomize