# ArgoCD Image Updater Configuration for GitOps Automation
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: jclee-registry
      api_url: https://registry.jclee.me
      prefix: registry.jclee.me
      insecure: no
      credentials: secret:argocd/harbor-registry#config
      default: true
      ping: true
  
  applications.conf: |
    applications:
    - name: fortinet
      images:
      - registry.jclee.me/fortinet
      update_strategy: semver
      write_back_method: git
      write_back_target: kustomization
      git_branch: master
      git_commit_message: |
        chore(gitops): update fortinet image to {{.NewTag}}
        
        GitOps automated image update:
        - Previous: {{.OldTag}}
        - New: {{.NewTag}}
        - Build: {{.SHA}}
        
        🤖 Automated by ArgoCD Image Updater
---
# ArgoCD Image Updater Annotations for Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet
  namespace: argocd
  annotations:
    # Image updater configuration
    argocd-image-updater.argoproj.io/image-list: |
      fortinet=registry.jclee.me/fortinet:~ai-features-v2
    argocd-image-updater.argoproj.io/fortinet.update-strategy: latest
    argocd-image-updater.argoproj.io/fortinet.allow-tags: |
      regexp:^ai-features-v2-\d{8}-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/write-back-target: |
      kustomization:registry.jclee.me/fortinet