apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fortinet.fullname" . }}
  labels:
    {{- include "fortinet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fortinet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fortinet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fortinet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.fortinet.webPort }}
              protocol: TCP
          env:
            - name: APP_MODE
              value: "{{ .Values.fortinet.appMode }}"
            - name: WEB_APP_PORT
              value: "{{ .Values.fortinet.webPort }}"
            - name: WEB_APP_HOST
              value: "{{ .Values.fortinet.webHost }}"
            - name: OFFLINE_MODE
              value: "{{ .Values.fortinet.offlineMode }}"
            {{- if .Values.fortinet.fortimanager.enabled }}
            - name: FORTIMANAGER_HOST
              value: "{{ .Values.fortinet.fortimanager.host }}"
            - name: FORTIMANAGER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "fortinet.fullname" . }}-secrets
                  key: fortimanager-api-key
                  optional: true
            {{- end }}
            {{- if .Values.fortinet.fortigate.enabled }}
            - name: FORTIGATE_HOST
              value: "{{ .Values.fortinet.fortigate.host }}"
            - name: FORTIGATE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "fortinet.fullname" . }}-secrets
                  key: fortigate-api-key
                  optional: true
            {{- end }}
            {{- if .Values.fortinet.itsm.enabled }}
            - name: ITSM_URL
              value: "{{ .Values.fortinet.itsm.url }}"
            - name: ITSM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "fortinet.fullname" . }}-secrets
                  key: itsm-api-key
                  optional: true
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_ENABLED
              value: "true"
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis-master"
            - name: REDIS_PORT
              value: "6379"
            {{- end }}
            {{- range .Values.extraEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: logs
              mountPath: /app/logs
            {{- if .Values.scripts.enabled }}
            - name: scripts
              mountPath: /app/scripts
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "fortinet.fullname" . }}-data
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "fortinet.fullname" . }}-logs
        {{- else }}
        - name: data
          emptyDir: {}
        - name: logs
          emptyDir: {}
        {{- end }}
        {{- if .Values.scripts.enabled }}
        - name: scripts
          configMap:
            name: {{ include "fortinet.fullname" . }}-scripts
            defaultMode: 0755
        {{- end }}
