apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
- ../../manifests

patchesStrategicMerge:
- deployment-patch.yaml

labels:
- includeSelectors: true
  pairs:
    app: fortinet
    cluster: secondary
    environment: production