apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: jclee-registry
      api_url: https://registry.jclee.me
      prefix: registry.jclee.me
      insecure: yes
      default: true
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  argocd.token: ""  # ArgoCD API token
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet
  namespace: argocd
  annotations:
    # ArgoCD Image Updater 설정
    argocd-image-updater.argoproj.io/image-list: fortinet=registry.jclee.me/fortinet:latest
    argocd-image-updater.argoproj.io/fortinet.update-strategy: latest
    argocd-image-updater.argoproj.io/fortinet.pull-secret: pullsecret:fortinet/regcred
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/fortinet
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true