apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fortinet
  namespace: fortinet
  labels:
    app: fortinet
  annotations:
    # NGINX specific settings
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    
    # TLS certificate management
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
    # Enable WebSocket support for SSE
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - fortinet.jclee.me
    secretName: fortinet-tls
  rules:
  - host: fortinet.jclee.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fortinet
            port:
              number: 7777