# Keel - Kubernetes Operator for automating image updates
# https://keel.sh/
---
apiVersion: v1
kind: Namespace
metadata:
  name: keel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keel
  namespace: keel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keel
rules:
- apiGroups: [""]
  resources: ["namespaces", "secrets", "configmaps", "services", "pods", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keel
subjects:
- kind: ServiceAccount
  name: keel
  namespace: keel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keel-config
  namespace: keel
data:
  config.yaml: |
    # Helm configuration
    helmProvider:
      enabled: false
    
    # Notification configuration (optional)
    slack:
      enabled: false
    
    # Webhook configuration
    webhook:
      enabled: true
      endpoint: http://localhost:9300
    
    # Registry settings
    registries:
      - name: jclee-registry
        url: https://registry.jclee.me
        username: ""  # Use secret instead
        password: ""  # Use secret instead
        insecure: true
    
    # Polling settings
    poll:
      defaultSchedule: "@every 1m"
      
    # Approval settings
    approvals:
      enabled: false  # Auto-approve all updates
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: keel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
    spec:
      serviceAccountName: keel
      containers:
      - name: keel
        image: keelhq/keel:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9300
          name: http
        env:
        - name: BASIC_AUTH_USER
          value: "admin"
        - name: BASIC_AUTH_PASSWORD
          value: "admin"
        - name: POLL
          value: "true"
        - name: HELM_PROVIDER
          value: "false"
        # Registry credentials
        - name: DOCKER_REGISTRY_SECRET
          value: "regcred"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: keel-config
---
apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: keel
spec:
  type: ClusterIP
  ports:
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: http
  selector:
    app: keel