apiVersion: v2
name: fortinet
description: Fortinet microservice on jclee.me infrastructure
type: application
version: 1.1.8
appVersion: "2.1.1"
keywords:
  - microservice
  - jclee.me
  - gitops
  - argocd
  - fortinet
  - network-security
home: https://fortinet.jclee.me
sources:
  - https://github.com/jclee/fortinet
maintainers:
  - name: jclee
    email: admin@jclee.me
annotations:
  category: microservice
  infrastructure: jclee.me
  security: network-monitoring