# MSA 기본 설정 (jclee.me 인프라 최적화)
replicaCount: 3
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

image:
  repository: registry.jclee.me/jclee/fortinet
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master-37900ce8"

imagePullSecrets:
  - name: jclee-registry-secret

service:
  type: NodePort
  port: 80
  targetPort: 7777  # Fortinet 애플리케이션 포트
  nodePort: 30777

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: fortinet.jclee.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fortinet-tls
      hosts:
        - fortinet.jclee.me

# MSA 리소스 최적화
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

# HPA (Horizontal Pod Autoscaler)
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Fortinet 애플리케이션 환경 변수
env:
  NODE_ENV: production
  WEB_APP_PORT: "7777"
  APP_MODE: production
  OFFLINE_MODE: "false"
  MICROSERVICE_NAME: fortinet
  CLUSTER_NAME: microservices-cluster
  NAMESPACE: microservices

# Health Check 설정 (Fortinet 애플리케이션 기준)
probes:
  liveness:
    path: /api/health
    port: 7777
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    path: /api/health
    port: 7777
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# MSA 보안 설정
securityContext:
  runAsNonRoot: false  # Fortinet 애플리케이션 요구사항
  runAsUser: 0
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

# Fortinet 애플리케이션 볼륨 설정
volumes:
  data:
    enabled: true
    size: 1Gi
    storageClass: standard
  logs:
    enabled: true
    size: 500Mi
    storageClass: standard

# MSA 모니터링 (Prometheus/Grafana)
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    path: /api/health
    port: metrics

# MSA 로깅 (ELK Stack)  
logging:
  enabled: true
  level: info
  format: json

# Fortinet 특화 설정
fortinet:
  mockMode: false
  apiKeys:
    fortigate: ""
    fortimanager: ""
  networking:
    enableSocketIO: true
    enableSSE: true