# MSA 기본 설정 (jclee.me 인프라 최적화)
replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

image:
  repository: registry.jclee.me/fortinet
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: harbor-registry

service:
  type: NodePort
  port: 80
  targetPort: 7777  # Fortinet 애플리케이션 포트
  nodePort: 30777

ingress:
  enabled: true
  className: traefik
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: fortinet.jclee.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fortinet-tls
      hosts:
        - fortinet.jclee.me

# MSA 리소스 최적화 (보안 강화)
resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 1Gi

# HPA (Horizontal Pod Autoscaler)
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85

# Fortinet 애플리케이션 환경 변수 (보안 강화)
env:
  NODE_ENV: production
  WEB_APP_PORT: "7777"
  APP_MODE: production
  OFFLINE_MODE: "false"
  MICROSERVICE_NAME: fortinet
  CLUSTER_NAME: microservices-cluster
  NAMESPACE: fortinet
  # 보안 설정 강화
  VERIFY_SSL: "true"
  SESSION_COOKIE_SECURE: "true"
  SESSION_COOKIE_HTTPONLY: "true"
  SESSION_COOKIE_SAMESITE: "Lax"
  PERMANENT_SESSION_LIFETIME: "900"  # 15분
  FORCE_DEBUG: "false"
  # JWT 보안 설정
  JWT_EXPIRES_IN: "900"  # 15분
  JWT_ALGORITHM: "HS256"
  JWT_ISSUER: "fortinet-app"
  JWT_AUDIENCE: "fortinet-api"
  # API 보안
  API_RATE_LIMIT_MAX: "100"
  API_RATE_LIMIT_WINDOW: "60"
  API_TIMEOUT: "30"
  # 로깅 보안
  LOG_LEVEL: "INFO"
  DISABLE_DEBUG_LOGS: "true"
  MASK_SENSITIVE_DATA: "true"

# Health Check 설정 (Fortinet 애플리케이션 기준)
probes:
  liveness:
    path: /api/health
    port: 7777
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    path: /api/health
    port: 7777
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# MSA 보안 설정 강화
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE  # 포트 바인딩만 허용
  seccompProfile:
    type: RuntimeDefault

# Fortinet 애플리케이션 볼륨 설정
volumes:
  data:
    enabled: false
    size: 1Gi
    storageClass: local-path
  logs:
    enabled: false
    size: 500Mi
    storageClass: local-path

# MSA 모니터링 (Prometheus/Grafana)
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    path: /api/health
    port: metrics

# MSA 로깅 (ELK Stack)  
logging:
  enabled: true
  level: info
  format: json

# Fortinet 특화 설정
fortinet:
  mockMode: false
  apiKeys:
    fortigate: ""
    fortimanager: ""
  networking:
    enableSocketIO: true
    enableSSE: true