# Production environment overrides
fortinet:
  appMode: "production"
  offlineMode: false

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

ingress:
  hosts: []
  tls: []

nodePortService:
  enabled: true
  nodePort: 30777