replicaCount: 1

image:
  repository: registry.jclee.me/fortinet
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: harbor-registry

service:
  type: NodePort
  port: 80
  targetPort: 7777
  nodePort: 30779  # New port for GitOps deployment

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: fortinet.jclee.me
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  APP_MODE: "production"
  WEB_APP_PORT: "7777"
  WEB_APP_HOST: "0.0.0.0"
  OFFLINE_MODE: "false"
  REDIS_ENABLED: "true"

persistence:
  enabled: false
  storageClass: "nfs-client"
  accessMode: ReadWriteOnce
  size: 5Gi
  paths:
    - name: data
      mountPath: /app/data
      subPath: data
    - name: logs
      mountPath: /app/logs
      subPath: logs

redis:
  enabled: false
  image: redis:7-alpine
  service:
    port: 6379

probes:
  liveness:
    path: /api/health
    port: 7777
    initialDelaySeconds: 60
    periodSeconds: 30
  readiness:
    path: /api/health
    port: 7777
    initialDelaySeconds: 10
    periodSeconds: 10
