# External-DNS Helm Values
# Cloudflare 예시

# DNS 제공자 설정
provider: cloudflare

# Cloudflare 인증
cloudflare:
  # API 토큰 방식 (권장)
  apiToken: "YOUR_CLOUDFLARE_API_TOKEN"
  # 또는 이메일/키 방식
  # email: "your-email@example.com"
  # apiKey: "YOUR_GLOBAL_API_KEY"
  
  # Zone 필터링 (선택사항)
  proxied: false  # Cloudflare 프록시 사용 여부

# 소스 설정
sources:
  - service      # LoadBalancer/NodePort 서비스 감시
  - ingress      # Ingress 감시
  - crd          # Custom Resources 감시 (선택사항)

# 도메인 필터 (특정 도메인만 관리)
domainFilters:
  - jclee.me
  - fortinet.jclee.me

# 레코드 타입
txtOwnerID: "fortinet-cluster"  # 소유권 확인용
txtPrefix: "external-dns-"      # TXT 레코드 접두사

# 정책 설정
policy: sync  # sync: 생성/업데이트/삭제, upsert-only: 생성/업데이트만

# 업데이트 주기
interval: 1m

# 로그 레벨
logLevel: info

# 메트릭 활성화
metrics:
  enabled: true
  serviceMonitor:
    enabled: true