apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortinet-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: fortinet
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: CLUSTER_NAME
          value: "primary"
        - name: DEPLOYMENT_ENV
          value: "production-primary"