# Development environment overrides
fortinet:
  appMode: "development"
  offlineMode: true

replicaCount: 1

autoscaling:
  enabled: false

resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "500m"

ingress:
  enabled: false

nodePortService:
  enabled: true
  nodePort: 30888

# Disable Redis in dev
redis:
  enabled: false

# Smaller storage in dev
persistence:
  size: 1Gi