apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet-dev

resources:
- ../../manifests

patchesStrategicMerge:
- namespace-patch.yaml
- service-patch.yaml

images:
- name: registry.jclee.me/fortinet
  newTag: dev-latest

commonLabels:
  environment: development

namePrefix: dev-