apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet-dev

resources:
- ../../manifests

patches:
- target:
    kind: Service
    name: fortinet-nodeport
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30880

images:
- name: registry.jclee.me/fortinet
  newTag: dev-latest

labels:
- includeSelectors: true
  pairs:
    environment: development