apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fortinet
  namespace: argocd
spec:
  generators:
  - clusters: {}  # 모든 등록된 클러스터에 자동 배포
  template:
    metadata:
      name: 'fortinet-{{name}}'
      labels:
        cluster: '{{name}}'
        environment: '{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/JCLEE94/fortinet.git
        targetRevision: HEAD
        path: k8s/manifests
        kustomize:
          images:
          - name: registry.jclee.me/fortinet
            newTag: latest
          replicas:
          - name: fortinet-app
            count: '{{values.replicas}}'
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        managedFieldsManagers:
        - kube-controller-manager