apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet
  namespace: argocd
  annotations:
    # ArgoCD Image Updater - 자동으로 최신 이미지 감지 및 업데이트
    argocd-image-updater.argoproj.io/image-list: fortinet=registry.jclee.me/fortinet:latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/fortinet.update-strategy: latest
    argocd-image-updater.argoproj.io/fortinet.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/fortinet.helm.image-tag: image.tag
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    targetRevision: "*"  # 최신 차트 버전 자동 사용
    chart: fortinet
    helm:
      # values 파일은 차트에 포함된 기본값 사용
      # 필요한 경우만 파라미터로 오버라이드
      parameters:
        # 필수 레지스트리 인증 정보만 여기에 지정
        - name: registryCredentials.username
          value: admin
        - name: registryCredentials.password
          value: bingogo1
        # 스토리지 클래스 수정
        - name: persistence.storageClass
          value: standard
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m