apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: fortinet=registry.jclee.me/fortinet:latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/fortinet.update-strategy: latest
    argocd-image-updater.argoproj.io/fortinet.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/fortinet.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    targetRevision: "*"
    chart: fortinet
    helm:
      # 환경에 따라 다른 values 파일 사용
      valueFiles:
        - values.yaml
        - values-prod.yaml  # 프로덕션 환경용
      # 런타임에 오버라이드할 파라미터만 지정
      parameters:
        - name: registryCredentials.username
          value: admin
        - name: registryCredentials.password
          value: bingogo1
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m