apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blacklist
  namespace: argocd
  labels:
    app: blacklist
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/fortinet.git
    targetRevision: HEAD
    path: k8s/blacklist
  destination:
    server: https://kubernetes.default.svc
    namespace: blacklist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true