apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet-development
  namespace: argocd
  annotations:
    # ArgoCD Image Updater - Development Environment
    argocd-image-updater.argoproj.io/image-list: fortinet=registry.jclee.me/fortinet:~dev-latest
    argocd-image-updater.argoproj.io/fortinet.update-strategy: latest
    argocd-image-updater.argoproj.io/fortinet.allow-tags: regexp:^(dev-.*|development-.*)$
    argocd-image-updater.argoproj.io/fortinet.pull-secret: fortinet-dev/registry-credentials
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: dev-updates
    argocd-image-updater.argoproj.io/fortinet.platforms: linux/amd64
    argocd-image-updater.argoproj.io/fortinet.ignore-tags: regexp:^(latest|v?\d+\.\d+\.\d+.*|production-.*|staging-.*)$
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/fortinet
    targetRevision: HEAD
    path: k8s/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
  health:
    enabled: true