apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: registry.jclee.me
      api_url: https://registry.jclee.me
      prefix: registry.jclee.me
      insecure: yes
      credentials: none
  # 로그 레벨 설정
  log.level: debug
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  # GitHub Token for webhook trigger
  github.token: ${{ secrets.GITHUB_TOKEN }}