apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: harbor
      api_url: https://registry.jclee.me
      prefix: registry.jclee.me
      insecure: yes
      credentials: pullsecret:fortinet/harbor-registry