apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet-secondary
  namespace: argocd
  labels:
    app.kubernetes.io/name: fortinet
    app.kubernetes.io/component: secondary
    app.kubernetes.io/part-of: fortinet-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/JCLEE94/fortinet.git
    targetRevision: HEAD
    path: k8s/manifests
    kustomize:
      replicas:
      - name: fortinet-app
        count: 2  # Secondary cluster: reduced replicas
  
  destination:
    server: https://192.168.50.110:6443  # Secondary cluster (when ready)
    namespace: fortinet
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  revisionHistoryLimit: 5
  
  # Health check configuration
  ignoreDifferences:
  - group: apps
    kind: Deployment
    managedFieldsManagers:
    - kube-controller-manager