apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet-production
  namespace: argocd
  annotations:
    # GitOps 4원칙 준수: ArgoCD Image Updater를 통한 불변 이미지 자동 업데이트
    argocd-image-updater.argoproj.io/image-list: fortinet=registry.jclee.me/fortinet
    argocd-image-updater.argoproj.io/fortinet.update-strategy: digest
    argocd-image-updater.argoproj.io/fortinet.allow-tags: regexp:^production-[0-9]{8}-[0-9]{6}.*$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/fortinet.pull-secret: pullsecret:argocd/harbor-registry
    # GitOps 메타데이터
    gitops.argocd.argoproj.io/managed: "true"
    gitops.principle.declarative: "true"
    gitops.principle.git-source: "https://github.com/JCLEE94/fortinet"
    gitops.principle.pull-based: "true"
    gitops.principle.immutable: "true"
  labels:
    app: fortinet
    environment: production
    gitops.strategy: pull-based
spec:
  project: default
  
  # GitOps 4원칙 준수: Git이 유일한 진실의 소스 (Git as Source of Truth)
  source:
    repoURL: https://github.com/JCLEE94/fortinet
    targetRevision: HEAD
    path: k8s/overlays/production
  
  # GitOps 4원칙 준수: Pull 기반 배포 (Pull-based Deployment)
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet-prod
  
  # GitOps 4원칙 준수: 완전 자동화된 Pull 기반 동기화
  syncPolicy:
    automated:
      prune: true      # 삭제된 리소스 자동 제거
      selfHeal: true   # 드리프트 자동 수정
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true           # 네임스페이스 자동 생성
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true       # 변경된 리소스만 적용
      - RespectIgnoreDifferences=true
      - ServerSideApply=false         # Client-side apply 사용
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # GitOps 베스트 프랙티스: 무시할 차이점 설정
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # HPA가 관리하는 replicas 무시
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP  # 자동 할당되는 ClusterIP 무시

  # 운영환경 전용 리비전 히스토리 설정
  revisionHistoryLimit: 10

  # 상태 체크 설정
  health:
    syncPolicy:
      - timeout: 120  # 2분 타임아웃