apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortinet
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: fortinet=registry.jclee.me/fortinet
    argocd-image-updater.argoproj.io/fortinet.update-strategy: latest
    argocd-image-updater.argoproj.io/fortinet.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    targetRevision: "*"  # Always use latest version
    chart: fortinet
    helm:
      releaseName: fortinet
      values: |
        replicaCount: 1
        
        image:
          repository: registry.jclee.me/fortinet
          tag: latest
          pullPolicy: Always
        
        service:
          type: NodePort
          port: 7777
          nodePort: 30777
        
        ingress:
          enabled: true
          className: traefik
          annotations: {}
          hosts:
            - host: fortinet.jclee.me
              paths:
                - path: /
                  pathType: Prefix
          tls: []
        
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        
        env:
          APP_MODE: production
          OFFLINE_MODE: "false"
          WEB_APP_PORT: "7777"
          FLASK_ENV: production
          
          # FortiGate Configuration - MUST SET THESE!
          FORTIGATE_HOST: "192.168.50.99"  # CHANGE THIS to your FortiGate IP
          FORTIGATE_USERNAME: "admin"
          FORTIGATE_PASSWORD: "fortinet123"  # CHANGE THIS to your password
          
          # FortiManager Configuration - MUST SET THESE!
          FORTIMANAGER_HOST: "192.168.50.100"  # CHANGE THIS to your FortiManager IP
          FORTIMANAGER_USERNAME: "admin"
          FORTIMANAGER_PASSWORD: "fortinet123"  # CHANGE THIS to your password
        
        redis:
          enabled: true
          persistence:
            enabled: true
            size: 1Gi
        
        persistence:
          enabled: true
          storageClass: ""
          size: 5Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: fortinet
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    refresh:
      interval: "5m"  # Check for new versions every 5 minutes
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m