apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-proxy-config
  namespace: fortinet
data:
  proxy-config.json: |
    {
      "proxy_settings": {
        "ssl": "flexible",
        "always_use_https": true,
        "automatic_https_rewrites": true,
        "opportunistic_encryption": true,
        "min_tls_version": "1.2",
        "browser_cache_ttl": 14400,
        "cache_level": "standard",
        "development_mode": false
      },
      "page_rules": [
        {
          "target": "fortinet.jclee.me/*",
          "actions": {
            "ssl": "flexible",
            "always_use_https": "on",
            "cache_level": "bypass"
          }
        }
      ],
      "firewall_rules": [
        {
          "name": "Allow NodePort Access",
          "expression": "(http.host eq \"fortinet.jclee.me\" and http.request.uri.path contains \"/api/\")",
          "action": "allow"
        }
      ]
    }