apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - pvc.yaml
  - redis.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: python
    newTag: 3.11-slim

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: argocd

commonAnnotations:
  app.kubernetes.io/version: "df5b6b3"
  deployed-by: "argocd-fix"
  deployed-at: "2025-07-07T12:18:50Z"