apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - pvc.yaml
  - redis.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: registry.jclee.me/fortinet
    newTag: b0ddd71

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: argocd

commonAnnotations:
  app.kubernetes.io/version: "b0ddd71"
  deployed-by: "argocd-fix"
  deployed-at: "2025-07-07T07:29:00Z"