apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - pvc.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - test-deployment.yaml

images:
  - name: registry.jclee.me/fortinet
    newTag: cafdec6

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: argocd

commonAnnotations:
  app.kubernetes.io/version: "cafdec6"
  deployed-by: "github-actions"
  deployed-at: "2025-07-04T16:30:00Z"