apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - cloudflare-tunnel-configmap.yaml
  - namespace.yaml
  - persistent-volumes.yaml
  - pvc.yaml
  - redis.yaml
  - configmap.yaml
  - registry-secret-generated.yaml
  - deployment-with-cloudflare.yaml
  - service.yaml

images:
  - name: registry.jclee.me/fortinet
    newName: registry.jclee.me/fortinet
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: argocd

commonAnnotations:
  app.kubernetes.io/version: "18bd5e0"
  deployed-by: "argocd-fix"
  deployed-at: "2025-07-08T11:19:29Z"