apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - pvc.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - test-deployment.yaml

# images:
#   - name: registry.jclee.me/fortinet
#     newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: argocd

commonAnnotations:
  app.kubernetes.io/version: "399ab07"
  deployed-by: "github-actions-manual-fix"
  deployed-at: "2025-07-05T00:11:00Z"