apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - pvc.yaml
  - redis.yaml
  - configmap.yaml
  - full-app-configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: fortinet
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: argocd

commonAnnotations:
  app.kubernetes.io/version: "cc7a16e"
  deployed-by: "argocd-fix"
  deployed-at: "2025-07-07T12:31:39Z"