apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - pvc.yaml
  - redis.yaml
  - configmap.yaml
  - registry-noauth-secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: registry.jclee.me/fortinet
    newName: registry.jclee.me/fortinet
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: fortinet
      managed-by: argocd

commonAnnotations:
  app.kubernetes.io/version: "79bcc91"
  deployed-by: "argocd-fix"
  deployed-at: "2025-07-08T12:13:53Z"