apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
  - namespace.yaml
  - secrets.yaml
  - pvc.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: registry.jclee.me/fortinet
    newTag: latest

commonLabels:
  app: fortinet
  managed-by: argocd