apiVersion: v1
kind: ConfigMap
metadata:
  name: npm-proxy-config
  namespace: fortinet
data:
  proxy-config.json: |
    {
      "domain": "fortinet.jclee.me",
      "upstream": {
        "service": "fortinet-nodeport",
        "namespace": "fortinet",
        "port": 30777
      },
      "npm": {
        "url": "http://npm.jclee.me",
        "proxy_host_id": ""
      }
    }
---
# CronJob으로 주기적으로 NPM 업데이트
apiVersion: batch/v1
kind: CronJob
metadata:
  name: npm-updater
  namespace: fortinet
spec:
  schedule: "*/5 * * * *"  # 5분마다 실행
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: npm-updater
          containers:
          - name: updater
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              # NodePort 확인
              NODE_PORT=$(kubectl get service fortinet-nodeport -n fortinet -o jsonpath='{.spec.ports[0].nodePort}')
              NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
              
              # ConfigMap 업데이트
              kubectl create configmap npm-current-config \
                --from-literal=node_ip=$NODE_IP \
                --from-literal=node_port=$NODE_PORT \
                --dry-run=client -o yaml | kubectl apply -f -
              
              echo "Updated NPM config: $NODE_IP:$NODE_PORT"
          restartPolicy: OnFailure
---
# ServiceAccount와 권한
apiVersion: v1
kind: ServiceAccount
metadata:
  name: npm-updater
  namespace: fortinet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: npm-updater
  namespace: fortinet
rules:
- apiGroups: [""]
  resources: ["services", "configmaps", "nodes"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: npm-updater
  namespace: fortinet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: npm-updater
subjects:
- kind: ServiceAccount
  name: npm-updater
  namespace: fortinet