apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortinet-data-pvc
  namespace: fortinet
  labels:
    app: fortinet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: fortinet
  labels:
    app: fortinet
    component: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""