apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: fortinet
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.jclee.me": {}
      }
    }