apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: fortinet
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "jclee94",
          "password": "github_pat_placeholder",
          "auth": ""
        },
        "registry.jclee.me": {}
      }
    }