apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortinet
  annotations:
    deployment.kubernetes.io/revision: "1"
    environment: production
spec:
  replicas: 1  # 리소스 제약으로 일시적으로 1개 인스턴스
  template:
    spec:
      containers:
      - name: fortinet
        env:
        - name: APP_MODE
          value: "production"
        - name: OFFLINE_MODE
          value: "false"  # 프로덕션에서는 실제 API 사용
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_ENABLED
          value: "true"
        - name: MONITORING_ENABLED
          value: "true"
        - name: SECRET_KEY
          value: "fortinet-production-secret-key-2025-secure-random-string-jclee-me"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: 500Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 7777
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 7777
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 7777
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 15