apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
- ../../base

images:
- name: registry.jclee.me/fortinet
  newTag: c2ab400-20250811-000259

labels:
- includeSelectors: true
  pairs:
    environment: production