apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
- ../../base

images:
- name: registry.jclee.me/fortinet
  newTag: latest  # ArgoCD에서 자동 업데이트

replicas:
- name: fortinet
  count: 2

patchesStrategicMerge:
- deployment-patch.yaml

labels:
- includeSelectors: true
  pairs:
    environment: production
    tier: backend
    gitops.strategy: pull-based

commonAnnotations:
  gitops.argocd.argoproj.io/managed: "true"
  environment: production
  deployment.strategy: rolling-update