apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# GitOps 4원칙 준수: 환경별 네임스페이스 분리
namespace: fortinet

resources:
- ../../base

# GitOps 4원칙 준수: 불변 이미지 태그 (Immutable Infrastructure)
# 동적 태그 형식: {version}-{date}-{git-sha}
images:
- name: registry.jclee.me/fortinet
  newTag: ai-features-v2

# 운영환경 설정 (고가용성을 위한 3개 인스턴스)
replicas:
- count: 3
  name: fortinet

# 운영환경 리소스 패치

# 환경별 명확한 라벨링
labels:
- includeSelectors: true
  pairs:
    deployment.type: blue-green
    environment: production
    gitops.environment: production
    gitops.strategy: pull-based
    monitoring.enabled: "true"
    stability: stable
    tier: backend

# GitOps 운영환경 메타데이터
commonAnnotations:
  deployment.maxSurge: 25%
  deployment.maxUnavailable: 25%
  deployment.strategy: rolling-update
  gitops.argocd.argoproj.io/managed: "true"
  gitops.environment: production
  gitops.immutable-tag: ai-features-v2
  gitops.stability: stable
  monitoring.prometheus.io/port: "7777"
  monitoring.prometheus.io/scrape: "true"
  security.policy: strict
patches:
- path: deployment-patch.yaml
