apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet

resources:
- ../../manifests

images:
- name: registry.jclee.me/fortinet
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    environment: production