apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fortinet-hpa
  namespace: fortinet-prod
  labels:
    app: fortinet
    component: autoscaler
    gitops.argocd.argoproj.io/managed: "true"
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","reason":"SucceededRescale"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":45}}]'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fortinet
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300  # 5분 안정화
      selectPolicy: Max
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300  # 5분 안정화
      selectPolicy: Min
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60