apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fortinet-base
  annotations:
    gitops.argocd.argoproj.io/managed: "true"

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: registry.jclee.me/fortinet
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: fortinet
    app.kubernetes.io/name: fortinet
    app.kubernetes.io/managed-by: argocd
    gitops.strategy: pull-based

commonAnnotations:
  gitops.argocd.argoproj.io/managed: "true"
  deployment.kubernetes.io/managed-by: "argocd"

namespace: fortinet