apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fortinet-base

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

images:
- name: registry.jclee.me/fortinet
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: fortinet
    version: "1.0.5"

namespace: fortinet