# Default values for fortinet-nextrade.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.jclee.me/fortinet
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: registry-credentials

nameOverride: ""
fullnameOverride: ""

# FortiGate Nextrade specific configuration
fortinet:
  appMode: "production"
  webPort: 7777
  webHost: "0.0.0.0"
  offlineMode: false
  
  # FortiManager Configuration
  fortimanager:
    enabled: true
    host: ""
    apiKey: ""
    
  # FortiGate Configuration
  fortigate:
    enabled: true
    host: ""
    apiKey: ""
    
  # ITSM Integration
  itsm:
    enabled: false
    url: ""
    apiKey: ""

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 7777
  
# NodePort service for external access
nodePortService:
  enabled: true
  type: NodePort
  port: 80
  nodePort: 30777
  targetPort: 7777

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: fortinet.jclee.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fortinet-tls
      hosts:
        - fortinet.jclee.me

# Resources
resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# Probes
livenessProbe:
  httpGet:
    path: /api/health
    port: 7777
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/health
    port: 7777
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Redis dependency
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi
  replica:
    replicaCount: 0

# Persistent storage
persistence:
  enabled: true
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 5Gi
  
# ConfigMap for scripts
scripts:
  enabled: true

# ServiceAccount
serviceAccount:
  create: false
  annotations: {}
  name: ""

# Security Context
podSecurityContext: {}
securityContext: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Extra environment variables
extraEnvVars: []
  # - name: CUSTOM_VAR
  #   value: "custom_value"

# Registry credentials
registryCredentials:
  create: true
  registry: registry.jclee.me
  username: admin
  password: bingogo1