apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortinet
  namespace: fortinet
  labels:
    app: fortinet
    managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortinet
  template:
    metadata:
      labels:
        app: fortinet
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7777"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: fortinet
        image: registry.jclee.me/fortinet:latest
        ports:
        - containerPort: 7777
          name: http
          protocol: TCP
        env:
        - name: APP_MODE
          value: "production"
        - name: WEB_APP_HOST
          value: "0.0.0.0"
        - name: WEB_APP_PORT
          value: "7777"
        - name: OFFLINE_MODE
          value: "false"
        - name: REDIS_ENABLED
          value: "true"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 7777
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 7777
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: fortinet-data
          mountPath: /app/data
        - name: fortinet-logs
          mountPath: /app/logs
        - name: fortinet-config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: fortinet-data
        persistentVolumeClaim:
          claimName: fortinet-data
      - name: fortinet-logs
        persistentVolumeClaim:
          claimName: fortinet-logs
      - name: fortinet-config
        configMap:
          name: fortinet-config
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000