apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortinet-data-pvc
  namespace: fortinet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortinet-logs-pvc
  namespace: fortinet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path