apiVersion: v1
kind: Service
metadata:
  name: fortinet-service
  namespace: fortinet
  labels:
    app: fortinet
    managed-by: argocd
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7777
    protocol: TCP
    name: http
  selector:
    app: fortinet
---
apiVersion: v1
kind: Service
metadata:
  name: fortinet-nodeport
  namespace: fortinet
  labels:
    app: fortinet
    service-type: external
    managed-by: argocd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 7777
    nodePort: 30777
    protocol: TCP
    name: http
  selector:
    app: fortinet