apiVersion: v1
kind: Service
metadata:
  name: fortinet
  namespace: fortinet
  labels:
    app: fortinet
spec:
  type: LoadBalancer
  ports:
  - port: 7777
    targetPort: 7777
    protocol: TCP
    name: http
  selector:
    app: fortinet