name: Minimal CI/CD (Free Tier)

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/ci-cd.yml'

env:
  REGISTRY: registry.jclee.me
  IMAGE_NAME: fortinet

jobs:
  build-deploy:
    name: 🚀 Quick Build & Deploy
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔐 Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: 🏗️ Build and Push
      run: |
        # Simple build without buildx to save runner time
        docker build -f Dockerfile.production \
          --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
          --build-arg GIT_COMMIT=${{ github.sha }} \
          --build-arg GIT_BRANCH=${{ github.ref_name }} \
          --build-arg VERSION=latest \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          .
        
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
    - name: 🔔 Trigger Deployment
      run: |
        curl -X POST https://watchtower.jclee.me/v1/update \
          -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" \
          || echo "Watchtower trigger failed"