{{- if .Values.registryCredentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  labels:
    {{- include "fortinet.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.registryCredentials.registry .Values.registryCredentials.username .Values.registryCredentials.password (printf "%s:%s" .Values.registryCredentials.username .Values.registryCredentials.password | b64enc) | b64enc }}
{{- end }}