apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet-staging

resources:
- ../../manifests

patchesStrategicMerge:
- namespace-patch.yaml
- service-patch.yaml

images:
- name: registry.jclee.me/fortinet
  newTag: staging-latest

commonLabels:
  environment: staging

namePrefix: staging-