apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fortinet-staging

resources:
- ../../base

patches:
- target:
    kind: Service
    name: fortinet-nodeport
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30881

images:
- name: registry.jclee.me/fortinet
  newTag: staging-latest

labels:
- includeSelectors: true
  pairs:
    environment: staging